name: Build and Deploy SPFX packages to Developer environment

on: 
  push: 
    branches: 
      main

jobs:
  build-and-deploy-webpart:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.19.0
    
    - name: Install from package-lock.json
      run: |
                npm ci
        # gulp bundle and package solution
    - name: Bundle and package
      run: |
        gulp bundle --debug
        gulp package-solution --ship    

    - name: Office 365 CLI Login
      uses: pnp/action-cli-login@v1.0.0
      with:
        ADMIN_USERNAME:  ${{ secrets.ADMINUSERNAME }}
        ADMIN_PASSWORD:  ${{ secrets.ADMINPASSWORD }}

    - name: Deploy to locations-dev app catalog
      uses: pnp/action-cli-deploy@v1.0.0
      with:
        APP_FILE_PATH: sharepoint/solution/permission-management.sppkg
        OVERWRITE: true
        SCOPE: sitecollection
        SITE_COLLECTION_URL: https://hhhhteams.sharepoint.com/sites/appcatalog
