name: SPFx Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Build solution
      run: npm run build --if-present
    - name: Package solution
      run: npm run package-solution --if-present
    - name: Deploy solution
      uses: PaoloPia/devops-deploy-spfx@v1
      with:
        environment: 'Dev'
        username: ${{ secrets.ADMINUSERNAME }}
        password: ${{ secrets.ADMINPASSWORD }}
